export const GET_DOGS_DATA_REQUEST = 'GET_DOGS_DATA_REQUEST';
export const GET_DOGS_DATA_SUCCESS = 'GET_DOGS_DATA_SUCCESS';
export const GET_DOGS_DATA_FAILURE = 'GET_DOGS_DATA_FAILURE';
export const GET_BREED_DATA_REQUEST = 'GET_BREED_DATA_REQUEST';
export const GET_BREED_DATA_SUCCESS = 'GET_BREED_DATA_SUCCESS';
export const GET_BREED_DATA_FAILURE = 'GET_BREED_DATA_FAILURE';